#!/bin/bash

BASEDIR=`pwd`

# load util functions
source ./lib/util.bash

# backup old .bashrc if it already exists
backupFile $HOME/.bashrc

# create new bashrc to load custom config
cat <<EOF>> $HOME/.bashrc
#!/bin/bash

# AUTOGENERATED
# DO NOT EDIT DIRECTLY
# https://github.com/anshulverma/bashrc

BASEDIR=$BASEDIR
export BASH_RC_BASEDIR=$BASEDIR
source $BASEDIR/bootstrap.bash

EOF
echo "created new $HOME/.bashrc"

# backup .bash_profile if it already exists
backupFile $HOME/.bash_profile

# create new bash_profile to load custom .bashrc
cat <<EOF>> $HOME/.bash_profile
#!/bin/bash

# AUTOGENERATED
# DO NOT EDIT DIRECTLY
# https://github.com/anshulverma/bashrc

# load bashrc in login shell
if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

EOF
echo "created new $HOME/.bash_profile"
